osx_image: xcode8
language: objective-c

cache:
  directories:
    - Carthage

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem update --system
  - gem install xcpretty -N

script:
  - set -o pipefail
  - brew update
  - brew upgrade xctool
  - brew upgrade carthage
  - ./bootstrap.sh
  - rm -rf build
  - xcodebuild -project Client.xcodeproj -scheme "Firefox" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6,OS=8.2" ONLY_ACTIVE_ARCH=NO -derivedDataPath build clean test | xcpretty -c
